version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    networks:
      - public_network
      - host_network  # Rede para acessar a API privada

  frontend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: react_app
      restart: always
      command: npm start
      ports:
        - "3000:3000"
      networks:
        - public_network

networks:
  public_network:
    driver: bridge
  host_network:
    driver: bridge
    # Configuração adicional se a API estiver em outra rede Docker:
    # external: true
    # name: rede-da-api