name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3
        continue-on-error: true

      # Instalar dependências do Node.js
      - name: Install Node.js dependencies
        run: |
          npm install
        continue-on-error: true

      # Build da aplicação Vite
      - name: Build Vite React App
        run: |
          npm run build
        continue-on-error: true

      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        continue-on-error: true

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true

      # Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t marcosfloriano/dashboard:latest .
        continue-on-error: true

      # Push da imagem para o Docker Hub
      - name: Push Docker Image
        run: |
          docker push marcosfloriano/dashboard:latest
        continue-on-error: true
